# Generated by Django 3.1.7 on 2021-11-16 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
